name: Build and Release

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - name: Install dependencies
          run: npm ci
        - name: Build the app
          run: npm run bild
        - name: Deploy
          uses: bitovi/github-actions-react-to-github-pages@v1.2.1
          with:
            path: build
  
  
      
