name: Build and Release

on:
  push:
    branches: 
    - master
  pull_request:
    branches: 
    - master

  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
        - uses: actions/checkout@v3
        - name: Install dependencies
          run: npm install
        - name: Build the app
          run: npm run build
        - name: Configure git to trust the workspace despite the different owner
          run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
        - name: Deploy
          uses: JamesIves/github-pages-deploy-action@v4.4.3
          with:
            folder: build
            
  
  
      
